language: node_js

services:
  - docker

jobs:
    include:
        - stage: build static application
          script: npm run build
        - stage: build docker image
          script: npm run build && docker build . -t latest-version && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push zniszcz/sample-ci-experiment