language: node_js

services:
  - docker

jobs:
    include:
        - stage: build static application
          script: npm run build
        - stage: build docker image
          script:
          - npm run build
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t sample-ci-experiment .
          - docker images
          - docker tag sample-ci-experiment $DOCKER_USERNAME/sample-ci-experiment
          - docker push $DOCKER_USERNAME/sample-ci-experiment